### PR TITLE
Knife plugin - better AMI granularity

### PR DESCRIPTION
**Pull request by vancluever**
Not too sure if this just changed with the times, but the knife plugin seems too general in its AMI output and is missing several kinds of images that exist now. This small PR adds granularity for HVM images, and the different kinds of EBS storage. I tried to do it so that it should not impact current use.

Sample of output now:

```
us_east_large:                    ami-0a7a3f60
us_east_large_ebs:                ami-7388cd19
us_east_large_ebs_hvm:            ami-0f8bce65
us_east_large_ebs_io1:            ami-548acf3e
us_east_large_ebs_io1_hvm:        ami-b988cdd3
us_east_large_ebs_ssd:            ami-0a8acf60
us_east_large_ebs_ssd_hvm:        ami-7b89cc11
us_east_large_hvm:                ami-9883c6f2
us_east_small:                    ami-2a6a2f40
us_east_small_ebs:                ami-988bcef2
us_east_small_ebs_io1:            ami-578acf3d
us_east_small_ebs_ssd:            ami-9295d0f8
```

### CODE REVIEW

**Comment by vancluever** [comment]
Any word on this PR?

**Comment by vancluever** [comment]
@jtimberman - Closing this - just throw me a comment or feel free to merge the commit if you need it still! I'll probably be dropping the branch though at some point in time when I prune old forked projects though.

**Comment by jtimberman** [comment]
Hello!

I'm so sorry that I missed this PR and never replied! I haven't worked with this plugin in quite some time. It seems reasonable, and I'll take a look at this later in the week.

Thank you,
Joshua

**Comment by vancluever** [comment]
Thanks @jtimberman! Hopefully it's still up to date, let me know if something needs fixing.

**Comment by jtimberman** [comment]
`rake test` isn't running, but probably due to changes in Minitest itself, since I haven't touched any of that in years.

**Pull request merged**
